# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "miniconda3-3.12-24.9"
  jobs:
    pre_build:
      - pip install versioneer[toml]==0.29
      - pip install . --no-deps --no-build-isolation

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: []

# Install pyiron from conda
conda:
  environment: .ci_support/environment-docs.yml
