channels:
- conda-forge
dependencies:
- coverage
- lammps =2025.07.22=*_mpi_mpich_*
- mpich =4.3.2
- numpy =2.4.6
- mpi4py =4.1.2
- executorlib =1.10.1
- ase =3.29.0
- scipy =1.17.1
- hatchling =1.31.0
- hatch-vcs =0.5.0
