channels:
- conda-forge
dependencies:
- lammps =2025.07.22=*_mpi_openmpi_*
- openmpi
- numpy =2.4.6
- mpi4py =4.1.2
- executorlib =1.9.0
- ase =3.23.0
- scipy =1.15.0
- pytorch-cpu
- hatchling
- hatch-vcs
