channels:
- conda-forge
dependencies:
- openmpi
- hatchling =1.30.1
- hatch-vcs =0.5.0
- numpy =2.4.6
- lammps =2025.07.22=*_mpi_openmpi_*
- mpi4py =4.1.2
- executorlib =1.10.1
- ase =3.29.0
- scipy =1.17.1
